{% set name = "wholeslidedata" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wholeslidedata-{{ version }}.tar.gz
  sha256: 544c3b8b5cb3973ce9e83b4c92a3acc74b8b51a68e02eb0acfe01d46cb918353

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - {{ cdt('mesa-libgl-devel') }}
    - python >={{ python_min }}
    - concurrentbuffer >=0.0.7
    - creationism >=0.0.5
    - numpy >=1.20.2
    - opencv >=4.4.0
    - scipy >=1.5.2
    - scikit-image >=0.17.2
    - shapely ==1.7.1
    - openslide-python >=1.1.1
    - pyyaml >=5.4.1
    - jsonschema >=4.4.0
    - rtree ==1.0.0
    - matplotlib-base >=3.6.2

test:
  imports:
    - wholeslidedata
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://diagnijmegen.github.io/pathology-whole-slide-data/
  summary: A package for working with whole-slide data including a fast batch iterator that can be used to train deep learning models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
